on: [push]

jobs:
  composite:
    runs-on: self-hosted
    name: Composite test
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: conorgomes-liatrio/bootcamp/composite@vComposite2
        with:
          who-to-greet: 'GORBLIN'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
