# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  workflow_dispatch:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "simple"
  simple:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo ${{ secrets.SECRET_PASSWORD }}

  generate-string:
    
    runs-on: ubuntu-latest

    outputs: 
        P_STR: ${{ env.P_STR }}
    steps:
      - name: Produce string
        run: echo "P_STR='stringy'" >> "$GITHUB_ENV"

  print-string:
    needs: [ generate-string ]
    runs-on: ubuntu-latest
    steps:
      - name: Print string
        run: echo ${{ needs.generate-string.outputs.P_STR }}

  matrix-print:
    needs: [ generate-string ]
    strategy:
      matrix: 
        num: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    runs-on: ubuntu-latest
    steps: 
      - name: Print string and num
        run: echo echo ${{ needs.generate-string.outputs.P_STR }} ${{ matrix.num }}