name: Reusable Workflow

on:
  workflow_call:
#    inputs:
#    secrets:


jobs:
  generate-string:
    runs-on: self-hosted
    steps:
      - name: Write file
        run: echo stringy > data.txt

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: word-string
          path: data.txt

  print-string:
    needs: [ generate-string ]
    runs-on: self-hosted
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: word-string
      - name: Print string
        run: cat data.txt
      - name: Store string
        run: echo "OUTSTR=$(cat data.txt)" >> "$GITHUB_ENV"

  matrix-print:
    needs: [ print-string ]
    strategy:
      matrix: 
        num: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    runs-on: self-hosted
    steps: 
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: word-string
      - name: Store string
        run: echo "OUTSTR=$(cat data.txt)" >> "$GITHUB_ENV"
      - name: Print string and num
        run: echo "$OUTSTR" ${{ matrix.num }}